# Generated by Django 5.0.2 on 2024-02-10 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("walks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="walkorder",
            name="walker",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
